use proydawii;

INSERT INTO `distrito` (`id`,`descripcion`) VALUES (1,'Ancón');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (2,'Ate');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (3,'Barranco');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (45,'Bellavista');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (4,'Breña');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (44,'Callao Cercado');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (5,'Carabayllo');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (46,'Carmen De La Legua');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (6,'Chaclacayo');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (7,'Chorrillos');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (8,'Cieneguilla');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (9,'Comas');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (10,'El Agustino');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (11,'Independencia');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (12,'Jesús María');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (13,'La Molina');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (47,'La Perla');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (48,'La Punta');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (14,'La Victoria');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (43,'Lima');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (15,'Lince');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (16,'Los Olivos');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (17,'Lurigancho-Chosica');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (18,'Lurín');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (19,'Magdalena Del Mar');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (21,'Miraflores');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (22,'Pachacámac');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (23,'Pucusana');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (20,'Pueblo Libre');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (24,'Puente Piedra');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (25,'Punta Hermosa');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (26,'Punta Negra');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (27,'Rímac');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (28,'San Bartolo');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (29,'San Borja');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (30,'San Isidro');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (31,'San Juan de Lurigancho');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (32,'San Juan de Miraflores');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (33,'San Luis');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (34,'San Martín de Porres');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (35,'San Miguel');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (36,'Santa Anita');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (37,'Santa María del Mar');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (38,'Santa Rosa');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (39,'Santiago de Surco');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (40,'Surquillo');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (49,'Ventanilla');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (41,'Villa El Salvador');
INSERT INTO `distrito` (`id`,`descripcion`) VALUES (42,'Villa María del Triunfo');
